name: CId

on: [push, workflow_dispatch]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Download Ngrok
    run: curl -sSL https://ngrok-agent.s3.amazonaws.com/ngrok.asc 
	run: sudo tee /etc/apt/trusted.gpg.d/ngrok.asc >/dev/null \
	run: sudo tee /etc/apt/sources.list.d/ngrok.list \
	run: sudo apt update \
	run:  sudo apt install ngrok
 
