name: CID

on: [pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Download ngrok
      run: Invoke-WebRequest https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-windows-amd64.zip -OutFile ngrok.zip

    - name: Extract ngrok
      run: Expand-Archive ngrok.zip

    - name: Auth ngrok
      run: .\ngrok\ngrok.exe config add-authtoken ${{ secrets.NGROK_AUTH_TOKEN }}
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}

    - name: Checkout código
      uses: actions/checkout@v2

    - name: Configurar Git
      run: |
        git config --global url."https://${{ secrets.GH_PAT }}@github.com/".insteadOf "https://github.com/"

    - name: Clonar repositorio privado
      run: git clone https://github.com/antolinnin/backend.git
      env:
        GH_PAT: ${{ secrets.GH_PAT }}

    - name: Instalar dependencias y ejecutar Strapi
      run: |
        cd backend
        npm install
        Start-Process npm -ArgumentList "run", "develop" -NoNewWindow

    - name: Crear túnel con ngrok
      run: .\ngrok\ngrok.exe tcp 1337
